### ISSUE TITLE
Server Installer not working

### ISSUE THREAD

**Issue by Gerald7777** [zehmaria/barely-an-assembly#1]
Due to cursemeta downfall, it's impossible to download server files.

**Comment by zehmaria** [comment]
I'll miss that one. It's a pain to do the other way. I should likely make the old one still when I can. For now I just deleted the file. 
I will keep this issue open until I can remember how to do the the big boy.
Thanks for notifying me. I saw the tragic news but didn't even think about the serverfiles. 
And I am on linux btw, so it's even worse for me, lol. My whole set up is crumbling.

PS: the cursemeta downfall sounded very poetic, I like it.

**Comment by zehmaria** [comment]
File is Under Review, and I don't think it's gonna be rejected, so closing this for now.
