### ISSUE TITLE
Going down with shift

### ISSUE THREAD

**Issue by fefolhes** [zehmaria/barely-an-assembly#3]
Is it right to press shift and go down the terrain? I keep doing that involuntarily almost every time.....

**Comment by zehmaria** [comment]
The ability is from the mod Origins. It's called phasing and can be toggled by using that mod's primary key, by default "g", but you can change the key in the config too. That ability is given if you chose the Engineer origin. You can notice if that's activated by the changed color of the screen. 

I hope this clarifies, if you have any other questions, please ask.

**Comment by zehmaria** [comment]
As of 1.5, this has been removed. It was far enough from what I wanted, and people being confused didn't help. Not worth keeping it. Maybe I would've keep it if adding dirt and stone to the blacklist wasn't so glitchy. In it's place, you now get a small extra inventory, by pressing "g" too.
